# Define global args
ARG RUNTIME_VERSION

# Build stage: compile Ruby and build the RIC gem
FROM public.ecr.aws/lambda/provided:al2023 AS build-image

ARG RUNTIME_VERSION

RUN dnf update -y && \
    dnf install -y git gcc gcc-c++ make openssl-devel readline-devel zlib-devel \
    libffi-devel libyaml-devel bzip2 autoconf automake libtool bison tar gzip

RUN rm -rf /root/.rbenv/
RUN git clone https://github.com/rbenv/rbenv.git /root/.rbenv
ENV PATH="/root/.rbenv/bin:$PATH"
RUN git clone https://github.com/rbenv/ruby-build.git /root/.rbenv/plugins/ruby-build
RUN RUNTIME_VERSIONS=($(rbenv install -L | grep -oE $(echo "^${RUNTIME_VERSION}\.[0-9]+"))) && \
    RUNTIME_LATEST_VERSION=${RUNTIME_VERSIONS[-1]} && \
    rbenv install -v ${RUNTIME_LATEST_VERSION} && \
    rbenv global ${RUNTIME_LATEST_VERSION} && \
    cp /root/.rbenv/versions/${RUNTIME_LATEST_VERSION}/bin/gem /usr/local/bin/gem && \
    cp /root/.rbenv/versions/${RUNTIME_LATEST_VERSION}/bin/rake /usr/local/bin/rake && \
    gem install bundler

ARG RIC_BUILD_DIR="/build"
RUN mkdir -p ${RIC_BUILD_DIR}
WORKDIR ${RIC_BUILD_DIR}
COPY . .
RUN rake build


# Runtime stage
FROM public.ecr.aws/lambda/provided:al2023

ARG RUNTIME_VERSION

RUN dnf install -y libyaml libxcrypt

# Copy ruby from the build-image
COPY --from=build-image /root/.rbenv /root/.rbenv
ENV PATH="/root/.rbenv/bin:$PATH"

# Copy the Runtime Interface Client gem and install it
ARG RIC_BUILD_DIR="/build"
COPY --from=build-image ${RIC_BUILD_DIR}/pkg/aws_lambda_ric*.gem aws_lambda_ric.gem
RUN RUNTIME_VERSIONS=($(rbenv install -L | grep -oE $(echo "^${RUNTIME_VERSION}\.[0-9]+"))) && \
    RUNTIME_LATEST_VERSION=${RUNTIME_VERSIONS[-1]} && \
    cp /root/.rbenv/versions/${RUNTIME_LATEST_VERSION}/bin/gem /usr/local/bin/gem && \
    gem install aws_lambda_ric.gem && \
    cp /root/.rbenv/versions/${RUNTIME_LATEST_VERSION}/bin/aws_lambda_ric /usr/local/bin/aws_lambda_ric

ARG FUNCTION_DIR="/function"
RUN mkdir -p ${FUNCTION_DIR}
COPY test/integration/test-handlers/echo/* ${FUNCTION_DIR}
WORKDIR ${FUNCTION_DIR}

ENTRYPOINT ["aws_lambda_ric"]
CMD ["app.App::Handler.process"]
