name: test-on-push-and-pr

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ '*' ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2
    - name: Set up ruby
      uses: ruby/setup-ruby@3ff19f5e2baf30647122352b96108b1fbe250c64 # v1
      with:
        ruby-version: 3.1
    - name: Run 'pr' target
      run: make pr
