name: test-on-push-and-pr

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ '*' ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7
    - name: Run 'pr' target
      run: make pr
